export const weatherTranslations: Record<string, any> = 
{
    de: {
        dirs: ["Norden", "Nordost", "Osten", "Südost", "Süden", "Südwest", "Westen", "Nordwest"],
        pollen: { none: "Keine", low: "Gering", moderate: "Mittel", high: "Hoch" },
        codes: {
            0: "Klarer Himmel",
            1: "Hauptsächlich klar",
            2: "Teilbewölkt",
            3: "Bedeckt",
            45: "Nebel",
            48: "Raureifnebel",
            51: "Leichter Niesel",
            53: "Mäßiger Niesel",
            55: "Dichter Niesel",
            56: "Leichter gefrierender Niesel",
            57: "Dichter gefrierender Niesel",
            61: "Leichter Regen",
            63: "Mäßiger Regen",
            65: "Starker Regen",
            66: "Leichter gefrierender Regen",
            67: "Starker gefrierender Regen",
            71: "Leichter Schneefall",
            73: "Mäßiger Schneefall",
            75: "Starker Schneefall",
            77: "Schneegriesel",
            80: "Leichte Regenschauer",
            81: "Mäßige Regenschauer",
            82: "Starke Regenschauer",
            85: "Leichte Schneeschauer",
            86: "Starke Schneeschauer",
            95: "Gewitter",
            96: "Gewitter mit leichtem Hagel",
            99: "Gewitter mit starkem Hagel"
        }
    },
    en: {
        dirs: ["North", "North-East", "East", "South-East", "South", "South-West", "West", "North-West"],
        pollen: { none: "None", low: "Low", moderate: "Moderate", high: "High" },
        codes: {
            0: "Clear sky", 
            1: "Mainly clear", 
            2: "Partly cloudy", 
            3: "Overcast",
            45: "Fog", 
            48: "Rime fog", 
            51: "Light drizzle", 
            53: "Moderate drizzle",
            55: "Dense drizzle", 
            56: "Light freezing drizzle", 
            57: "Dense freezing drizzle",
            61: "Slight rain", 
            63: "Moderate rain", 
            65: "Heavy rain",
            66: "Light freezing rain", 
            67: "Heavy freezing rain",
            71: "Slight snow", 
            73: "Moderate snow", 
            75: "Heavy snow",
            77: "Snow grains", 
            80: "Slight rain showers", 
            81: "Moderate rain showers",
            82: "Violent rain showers", 
            85: "Slight snow showers", 
            86: "Heavy snow showers",
            95: "Thunderstorm", 
            96: "Thunderstorm with slight hail", 
            99: "Thunderstorm with heavy hail"
        }
    },
    pl: {
        dirs: ["Północ", "Północny-wschód", "Wschód", "Południowy-wschód", "Południe", "Południowy-zachód", "Zachód", "Północny-zachód"],
        pollen: { none: "Brak", low: "Niski", moderate: "Średni", high: "Wysoki" },
        codes: {
            0: "Czyste niebo",
            1: "Głównie bezchmurnie",
            2: "Częściowe zachmurzenie",
            3: "Zachmurzenie całkowite",
            45: "Mgła",
            48: "Mgła osadzająca szron",
            51: "Lekka mżawka",
            53: "Umiarkowana mżawka",
            55: "Gęsta mżawka",
            56: "Lekka marznąca mżawka",
            57: "Gęsta marznąca mżawka",
            61: "Słaby deszcz",
            63: "Umiarkowany deszcz",
            65: "Silny deszcz",
            66: "Lekki marznący deszcz",
            67: "Silny marznący deszcz",
            71: "Słabe opady śniegu",
            73: "Umiarkowane opady śniegu",
            75: "Silne opady śniegu",
            77: "Ziarna śniegu",
            80: "Słabe przelotne opady deszczu",
            81: "Umiarkowane przelotne opady deszczu",
            82: "Gwałtowne przelotne opady deszczu",
            85: "Słabe przelotne opady śniegu",
            86: "Silne przelotne opady śniegu",
            95: "Burza",
            96: "Burza z lekkim gradem",
            99: "Burza z silnym gradem"
        }
    },
    ru: {
        dirs: ["Север", "Северо-восток", "Восток", "Юго-восток", "Юг", "Юго-запад", "Запад", "Северо-запад"],
        pollen: { none: "Нет", low: "Низкий", moderate: "Средний", high: "Высокий" },
        codes: {
            0: "Ясное небо",
            1: "Преимущественно ясно",
            2: "Переменная облачность",
            3: "Пасмурно",
            45: "Туман",
            48: "Ледяной туман",
            51: "Легкая морось",
            53: "Умеренная морось",
            55: "Плотная морось",
            56: "Легкая ледяная морось",
            57: "Плотная ледяная морось",
            61: "Небольшой дождь",
            63: "Умеренный дождь",
            65: "Сильный дождь",
            66: "Легкий ледяной дождь",
            67: "Сильный ледяной дождь",
            71: "Небольшой снег",
            73: "Умеренный снег",
            75: "Сильный снег",
            77: "Снежные зерна",
            80: "Небольшой ливневый дождь",
            81: "Умеренный ливневый дождь",
            82: "Сильный ливневый дождь",
            85: "Небольшой ливневый снег",
            86: "Сильный ливневый снег",
            95: "Гроза",
            96: "Гроза с небольшим градом",
            99: "Гроза с сильным градом"
        }
    },
    fr: {
        dirs: ["Nord", "Nord-Est", "Est", "Sud-Est", "Sud", "Sud-Ouest", "Ouest", "Nord-Ouest"],
        pollen: { none: "Aucun", low: "Faible", moderate: "Modéré", high: "Élevé" },
        codes: {
            0: "Ciel dégagé",
            1: "Principalement clair",
            2: "Partiellement nuageux",
            3: "Couvert",
            45: "Brouillard",
            48: "Brouillard givrant",
            51: "Bruine légère",
            53: "Bruine modérée",
            55: "Bruine dense",
            56: "Bruine verglaçante légère",
            57: "Bruine verglaçante dense",
            61: "Pluie légère",
            63: "Pluie modérée",
            65: "Pluie forte",
            66: "Pluie verglaçante légère",
            67: "Pluie verglaçante forte",
            71: "Chute de neige légère",
            73: "Chute de neige modérée",
            75: "Chute de neige forte",
            77: "Neige en grains",
            80: "Averses de pluie légères",
            81: "Averses de pluie modérées",
            82: "Averses de pluie violentes",
            85: "Averses de neige légères",
            86: "Averses de neige fortes",
            95: "Orage",
            96: "Orage avec grêle légère",
            99: "Orage avec grêle forte"
        }
    },
    it: {
        dirs: ["Nord", "Nord-Est", "Est", "Sud-Est", "Sud", "Sud-Ovest", "Ovest", "Nord-Ovest"],
        pollen: { none: "Nessuno", low: "Basso", moderate: "Moderato", high: "Alto" },
        codes: {
            0: "Cielo sereno",
            1: "Prevalentemente sereno",
            2: "Parzialmente nuvoloso",
            3: "Coperto",
            45: "Nebbia",
            48: "Nebbia con brina",
            51: "Pioggerellina leggera",
            53: "Pioggerellina moderata",
            55: "Pioggerellina densa",
            56: "Pioggerellina gelata leggera",
            57: "Pioggerellina gelata densa",
            61: "Pioggia debole",
            63: "Pioggia moderata",
            65: "Pioggia forte",
            66: "Pioggia gelata debole",
            67: "Pioggia gelata forte",
            71: "Neve debole",
            73: "Neve moderata",
            75: "Neve forte",
            77: "Granelli di neve",
            80: "Rovesci di pioggia deboli",
            81: "Rovesci di pioggia moderati",
            82: "Rovesci di pioggia violenti",
            85: "Rovesci di neve deboli",
            86: "Rovesci di neve forti",
            95: "Temporale",
            96: "Temporale con grandine debole",
            99: "Temporale con grandine forte"
        }
    },
    es: {
        dirs: ["Norte", "Noreste", "Este", "Sureste", "Sur", "Suroeste", "Oeste", "Noroeste"],
        pollen: { none: "Ninguno", low: "Bajo", moderate: "Moderado", high: "Alto" },
        codes: {
            0: "Cielo despejado",
            1: "Principalmente despejado",
            2: "Parcialmente nublado",
            3: "Nublado",
            45: "Niebla",
            48: "Niebla escarchada",
            51: "Llovizna ligera",
            53: "Llovizna moderada",
            55: "Llovizna densa",
            56: "Llovizna gélida ligera",
            57: "Llovizna gélida densa",
            61: "Lluvia débil",
            63: "Lluvia moderada",
            65: "Lluvia fuerte",
            66: "Lluvia gélida ligera",
            67: "Lluvia gélida fuerte",
            71: "Nieve débil",
            73: "Nieve moderada",
            75: "Nieve forte",
            77: "Granos de nieve",
            80: "Chubascos de lluvia ligeros",
            81: "Chubascos de lluvia moderados",
            82: "Chubascos de lluvia violentos",
            85: "Chubascos de nieve ligeros",
            86: "Chubascos de nieve fuertes",
            95: "Tormenta",
            96: "Tormenta con granizo débil",
            99: "Tormenta con granizo fuerte"
        }
    },
    zh: {
        dirs: ["北", "东北", "东", "东南", "南", "西南", "西", "西北"],
        pollen: { none: "无", low: "低", moderate: "中等", high: "高" },
        codes: {
            0: "晴朗",
            1: "大部晴朗",
            2: "多云",
            3: "阴天",
            45: "雾",
            48: "雾凇",
            51: "微毛毛雨",
            53: "中等毛毛雨",
            55: "浓毛毛雨",
            56: "轻微冻毛毛雨",
            57: "浓冻毛毛雨",
            61: "小雨",
            63: "中雨",
            65: "大雨",
            66: "轻微冻雨",
            67: "大冻雨",
            71: "小雪",
            73: "中雪",
            75: "大雪",
            77: "雪粒",
            80: "轻微阵雨",
            81: "中等阵雨",
            82: "剧烈阵雨",
            85: "小阵雪",
            86: "大阵雪",
            95: "雷暴",
            96: "雷暴伴有小冰雹",
            99: "雷暴伴有大冰雹"
        }
    },
    pt: {
        dirs: ["Norte", "Nordeste", "Este", "Sudeste", "Sul", "Sudoeste", "Oeste", "Noroeste"],
        pollen: { none: "Nenhum", low: "Baixo", moderate: "Moderado", high: "Alto" },
        codes: {
            0: "Céu limpo",
            1: "Principalmente limpo",
            2: "Parcialmente nublado",
            3: "Encoberto",
            45: "Nevoeiro",
            48: "Nevoeiro com geada",
            51: "Chuvisco leve",
            53: "Chuvisco moderado",
            55: "Chuvisco denso",
            56: "Chuvisco gelado leve",
            57: "Chuvisco gelado denso",
            61: "Chuva fraca",
            63: "Chuva moderada",
            65: "Chuva forte",
            66: "Chuva gelada leve",
            67: "Chuva gelada forte",
            71: "Neve fraca",
            73: "Neve moderada",
            75: "Neve forte",
            77: "Grãos de neve",
            80: "Aguaceiros leves",
            81: "Aguaceiros moderados",
            82: "Aguaceiros violentos",
            85: "Aguaceiros de neve leves",
            86: "Aguaceiros de neve fortes",
            95: "Trovoada",
            96: "Trovoada com granizo leve",
            99: "Trovoada com granizo forte"
        }
    }
};